AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 22

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'lib/warden/ldap/user_factory.rb'
